[package]
name = "morphorm"
version = "0.1.0"
edition = "2018"
author = "George Atkinson"
license = "MIT"
description = "A UI layout engine"
repository = "https://github.com/geom3trik/morphorm"
keywords = ["ui", "gui", "layout"]


[dependencies]
smallvec = "1.6.1"


[dev-dependencies]
morphorm-ecs = {version = "0.1.0", path = "ecs"}
winit = { version = "0.25", default-features = false }
femtovg = {version = "0.2.2", default-features = false}
glutin = "0.27.0"