[package]
name = "morphorm-ecs"
version = "0.1.0"
edition = "2018"

[dependencies]
morphorm = {version = "0.1.0", path = "../"}
raw-window-handle = "0.3.3"
rand = "0.8.4"
femtovg = "0.2.2"
glutin = "0.27.0"